# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Simone Mazzoleni Ferracini
title: Functional Analyst and Data Scientist
email: mazzolenif.simone@gmail.com
website: https://mazzolenifsimone.github.io/
# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: SimoneFerracini
github_username:  mazzolenifsimone
# stackoverflow_username: --
# dribbble_username: --
# facebook_username: --
# flickr_username: --
instagram_username: simomazzferr
linkedin_username: simone-mazzoleni-ferracini
# xing_username: --
# pinterest_username: --
# youtube_username: --
# googleplus_username: --
# orcid_username: --

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-3CW23CC602"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/FT_SimoneMazzoleniFerracini.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Simone and I am a Mathematical Engineer and problem solver. I applied my knowledge mainly on data science and functional analysis.
  
  I am mostly skilled in <mark>spreadsheet development</mark>, <mark>MATLAB</mark> and <mark>Python</mark>.

  

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Reti S.p.A.
        link: https://www.reti.it/
        link_text: reti.it
        sub_title: Functional Analyst, Data Scientist
        caption: 2017 - Present
#        quote: >
        description: | # this will include new lines to allow paragraphs
           In Reti S.p.A I am a functional analysis consultant and data scientist, mainly for big insurance companies.
           I learned how to menage custom projects in partership with the client, starting from client's needs, passing through design and development of solution and ending with solution reporting. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: left
      title: Politecnico di Milano
      caption: 2012 - 2017
      sub_title: MSc Method and Models for the Decision Making
#      quote: >
#         Where applied statistics and data science meets information tecnology
      description: | # this will include new lines to allow paragraphs
         During my last years at Politecnico di Milano I deepened theoretichal knowledge on mathematics, statistics and algorithmics and tested them on practical projects. 
         In my thesis I approached the energy consumption problem on smart grid. I re-designed a mixed-integer linear programming model and developed in Python some greedy local search alogorithms to find near optimal solutions.
         

    - layout: left
      title: Politecnico di Milano
      caption: 2008 - 2012
      sub_title: BSc Mathematical Engineering
#      quote: >
#       Where applied statistics and data science meets information tecnology: 
      description: | # this will include new lines to allow paragraphs
         My early years at Politecnico di Milano were mainly focused on learning the fundamental knowledge of mathematics, physics, statistics, finance and programming with <mark>C++</mark> and <mark>R</mark>.
         I graduated in 2012 with a thesis on a numerical approach for portfolio optimization with Matlab.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Afterclaps.com
        caption: 2014 - 2015
        link: https://youtu.be/zXbEzZRmLhY
        link_text: Project YouTube
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Afterclaps.com: the new way of making, knowing and talking about music
        description: | # this will include new lines to allow paragraphs
           Afterclaps aimed to be the first aggregator of social networks, focused on emerging music. A virtual stage where the users could share music, videos and emotions. Afterclaps allowed users to collect all the artistic contents of their Facebook, YouTube, Twitter and SoundCloud accounts.
           I was involved in the project as data scientist and I designed a set of popularity metrics in order to draw up an artists ranking list.

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#       WIP
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#     Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
